from __future__ import annotations

PACKAGE_VERSION = "1.12.0"
RENDER_SCHEMA_VERSION = "1.10"
BENCHMARK_SCHEMA_VERSION = "1.10"

__all__ = ["PACKAGE_VERSION", "RENDER_SCHEMA_VERSION", "BENCHMARK_SCHEMA_VERSION"]
