from __future__ import annotations

PACKAGE_VERSION = "1.16.0"
RENDER_SCHEMA_VERSION = "1.11"
BENCHMARK_SCHEMA_VERSION = "1.11"

__all__ = ["PACKAGE_VERSION", "RENDER_SCHEMA_VERSION", "BENCHMARK_SCHEMA_VERSION"]
