from __future__ import annotations
from pathlib import Path
import html
import numpy as np
from .tactile import geometry_report

def export_svg(binary, cfg, path, title='Braille Dot-Matrix Export'):
    b = np.asarray(binary, dtype=bool)
    spacing = float(cfg.dot_spacing_mm)
    radius = float(cfg.dot_radius_mm)
    width = b.shape[1] * spacing
    height = b.shape[0] * spacing
    lines = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width:.3f}mm" height="{height:.3f}mm" viewBox="0 0 {width:.3f} {height:.3f}">',
        f'<title>{html.escape(title)}</title>',
        '<metadata>Generated by braille-dotmatrix-engine tactile SVG export</metadata>',
        '<rect x="0" y="0" width="100%" height="100%" fill="white"/>',
    ]
    for y, x in np.argwhere(b):
        cx = (float(x) + 0.5) * spacing
        cy = (float(y) + 0.5) * spacing
        lines.append(f'<circle cx="{cx:.3f}" cy="{cy:.3f}" r="{radius:.3f}" fill="black"/>')
    report = geometry_report(cfg)
    lines.append(f'<!-- compliant={report["compliant"]} edge_gap_mm={report["edge_gap_mm"]:.3f} -->')
    lines.append('</svg>')
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    Path(path).write_text('\n'.join(lines), encoding='utf-8')
    return {'path': str(path), 'width_mm': width, 'height_mm': height, 'dot_count': int(np.count_nonzero(b)), 'geometry': report}
