from __future__ import annotations

from pathlib import Path
import html
import numbers
import numpy as np

from .geometry import compensated_dot_radius_mm
from .tactile import geometry_report


def _require_int_positive(name: str, value) -> int:
    if isinstance(value, bool) or not isinstance(value, numbers.Integral):
        raise ValueError(f'{name} must be an integer')
    parsed = int(value)
    if parsed <= 0:
        raise ValueError(f'{name} must be positive')
    return parsed


def _as_binary_matrix(binary, cfg=None) -> np.ndarray:
    b = np.asarray(binary, dtype=bool)
    if b.ndim != 2:
        raise ValueError('binary must be a 2D dot matrix')
    if b.size == 0 or b.shape[0] <= 0 or b.shape[1] <= 0:
        raise ValueError('binary dot matrix must be non-empty')
    if cfg is not None:
        limit = getattr(cfg, 'max_total_dots', None)
        if limit is not None and b.size > _require_int_positive('max_total_dots', limit):
            raise ValueError(f'binary dot matrix too large: {b.size} dots exceeds max_total_dots={limit}')
    return b


def export_svg(binary, cfg, path, title='Braille Dot-Matrix Export'):
    b = _as_binary_matrix(binary, cfg)
    spacing = float(cfg.dot_spacing_mm)
    radius = compensated_dot_radius_mm(cfg)
    width = b.shape[1] * spacing
    height = b.shape[0] * spacing
    lines = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width:.3f}mm" height="{height:.3f}mm" viewBox="0 0 {width:.3f} {height:.3f}">',
        f'<title>{html.escape(title)}</title>',
        '<metadata>Generated by braille-dotmatrix-engine tactile SVG export</metadata>',
        '<rect x="0" y="0" width="100%" height="100%" fill="white"/>',
    ]
    for y, x in np.argwhere(b):
        cx = (float(x) + 0.5) * spacing
        cy = (float(y) + 0.5) * spacing
        lines.append(f'<circle cx="{cx:.3f}" cy="{cy:.3f}" r="{radius:.3f}" fill="black"/>')
    report = geometry_report(cfg)
    lines.append(f'<!-- compliant={report["compliant"]} edge_gap_mm={report["edge_gap_mm"]:.3f} compensated_dot_radius_mm={radius:.3f} -->')
    lines.append('</svg>')
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    Path(path).write_text('\n'.join(lines), encoding='utf-8')
    return {
        'path': str(path),
        'width_mm': width,
        'height_mm': height,
        'dot_count': int(np.count_nonzero(b)),
        'compensated_dot_radius_mm': radius,
        'geometry': report,
    }
